[package]
name = "bench_pref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4.0"
pprof = { version = "0.3", features = ["flamegraph"] }